version: '3.8'

services:
  hsqldb:
    build: .
    container_name: hsqldb-server
    ports:
      - "9001:9001"
    volumes:
      - ./hsqldb-data:/opt/hsqldb/data
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: unless-stopped
  hsqldb-python-client:
    build:
      context: clients/python/
    depends_on:
      hsqldb:
        condition: service_healthy
    volumes:
      - ./clients/python/:/app/
      - /app/.venv
    container_name: hsqldb-python-client
