[project]
name = "hsqldb-python-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy>=2.0.41",
    "sqlalchemy-hsqldb>=0.2.1",
]
